import re
import time
import requests
import pandas as pd

from scrapers.base.toyota_base import ToyotaBaseScraper


class ToyotaSantaMonicaScraper(ToyotaBaseScraper):
    dealer_name = "Toyota Santa Monica"
    specials_url = "https://www.toyotasantamonica.com/promotions/new/index.htm"
    api_url = "https://www.toyotasantamonica.com/api/widget/ws-specials/promos"

    HEADERS = {
        "accept": "*/*",
        "content-type": "application/json;charset=UTF-8",
        "origin": "https://www.toyotasantamonica.com",
        "referer": "https://www.toyotasantamonica.com/promotions/new/index.htm",
        "user-agent": "Mozilla/5.0",
        "x-page-id": "toyotasantamonicaca_SITEBUILDER_PROMOTIONS_LISTING_V3_NEW",
        "x-page-name": "PROMOTIONS_LISTING_NEW",
        "x-page-path": "/promotions/new/index.htm",
    }

    PAYLOAD = {
        "parameters": {
            "promoRO": {
                "accountId": "toyotasantamonicaca",
                "deviceType": "DESKTOP",
                "locale": "en_US",
                "autoGeneratedSpecialLimit": "0",
                "types": ["vehicle", "incentive"],
                "placements": "listing",
            },
            "filterRO": {
                "limitByInventory": "true",
                "limitByTags": [],
                "limitByTagsType": "INCLUDE",
                "listingConfigId": "auto-new",
                "specialCount": "30",
                "excludeModelOffersWithoutPhotos": "false",
                "vehicleId": "",
            },
            "eo": {
                "pixallId": "xBzPvgXhZ2oHtSojH6BON5Ol",
                "enablePersonalization": "true",
            },
            "removeVcdaRequest": "true",
            "requireAccountInfo": "true",
        }
    }

    def fetch_df(self) -> pd.DataFrame:
        session = requests.Session()

        # warmup for cookies / akamai
        session.get(
            self.specials_url,
            headers={"User-Agent": self.HEADERS["user-agent"]},
            timeout=30,
        )

        data = None
        last_err = None

        for _ in range(3):
            try:
                resp = session.post(
                    self.api_url,
                    json=self.PAYLOAD,
                    headers=self.HEADERS,
                    timeout=30,
                )
                resp.raise_for_status()
                data = resp.json()
                break
            except Exception as e:
                last_err = e
                time.sleep(0.6)

        if data is None:
            raise RuntimeError(f"Santa Monica promos API failed: {last_err!r}")

        rows = []
        promos = data.get("promos", []) or []

        for promo in promos:
            # keep vehicle promos only
            promo_type = (promo.get("type") or promo.get("promoType") or "").lower()
            if promo_type and promo_type != "vehicle":
                continue

            disclaimer = promo.get("disclaimer", "") or ""

            # must be a lease ($X per month)
            if not re.search(r"\$\s*\d[\d,]*\s*per\s*month", disclaimer, re.I):
                continue

            title = promo.get("title") or promo.get("model") or promo.get("name")
            expires = promo.get("endDateDisplay") or promo.get("endDate")

            rows.append({
                "Model": title,
                "Monthly ($)": self.money_to_int(
                    self.extract(r"\$(\d{1,4})\s*per\s*month", disclaimer)
                ),
                "Term (months)": (
                    self.money_to_int(self.extract(r"for\s*(\d+)\s*months", disclaimer))
                    or self.money_to_int(self.extract(r"(\d+)\s*month\s+lease", disclaimer))
                ),
                "Due at Signing ($)": self.money_to_int(
                    self.extract(r"\$([\d,]+)\s*Due\s*At\s*Signing", disclaimer)
                ),
                "MSRP ($)": (
                    self.money_to_int(self.extract(r"TSRP\s*\$([\d,]+)", disclaimer))
                    or self.money_to_int(self.extract(r"Total\s*SRP\s*\$([\d,]+)", disclaimer))
                    or self.money_to_int(self.extract(r"\bMSRP\s*\$([\d,]+)", disclaimer))
                ),
                "Expires": expires,
                "Dealer Specials Link": self.specials_url,
            })

        return pd.DataFrame(rows)

