import re
import requests
import pandas as pd
from scrapers.base.toyota_base import ToyotaBaseScraper


URL = "https://www.torrancetoyota.com/api/widget/ws-specials/promos"

HEADERS = {
    "Content-Type": "application/json",
    "Accept": "application/json",
    "User-Agent": "Mozilla/5.0",
}

PAYLOAD = {
    "parameters": {
        "promoRO": {
            "accountId": "dchtorrancetoyota",
            "deviceType": "DESKTOP",
            "locale": "en_US",
            "autoGeneratedSpecialLimit": "0",
            "types": ["vehicle", "incentive"],
            "placements": "listing"
        },
        "filterRO": {
            "limitByInventory": "true",
            "limitByTags": [],
            "limitByTagsType": "INCLUDE",
            "listingConfigId": "auto-new",
            "specialCount": "30",
            "excludeModelOffersWithoutPhotos": False,
            "vehicleId": ""
        },
        "eo": {
            "pixallId": "",
            # Enable personalization
        },
        # Remove Vcda request
        # Require account info
    }
}


class ToyotaTorranceScraper(ToyotaBaseScraper):
    dealer_name = "DCH Toyota of Torrance"
    specials_url = "https://www.torrancetoyota.com/promotions/new/index.htm"

    def fetch_df(self) -> pd.DataFrame:
        resp = requests.post(URL, json=PAYLOAD, headers=HEADERS, timeout=15)
        resp.raise_for_status()
        data = resp.json()

        rows = []

        for promo in data.get("promos", []):
            disclaimer = promo.get("disclaimer", "") or ""

            rows.append({
                "Model": promo.get("title"),
                "Monthly ($)": self.money_to_int(
                    self.extract(r"\$(\d+)\s*per\s*month", disclaimer)
                ),
                "Term (months)": self.money_to_int(
                    self.extract(r"for\s*(\d+)\s*months", disclaimer)
                ),
                "Due at Signing ($)": self.money_to_int(
                    self.extract(r"\$([\d,]+)\s*Due\s*At\s*Signing", disclaimer)
                ),
                "MSRP ($)": self.money_to_int(
                    self.extract(r"TSRP\s*\$([\d,]+)", disclaimer)
                ),
                "Expires": promo.get("endDateDisplay"),
                "Dealer Specials Link": self.specials_url,
            })

        return pd.DataFrame(rows)

